services:
  # Database (shared)
  postgres:
    image: postgres:15
    container_name: stock-postgres
    environment:
      POSTGRES_DB: stock_monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - stock_postgres_data:/var/lib/postgresql/data
      - ./scripts/init-schemas.sql:/docker-entrypoint-initdb.d/init-schemas.sql
    networks:
      - stock-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: stock-redis
    ports:
      - "6379:6379"
    networks:
      - stock-network

  zookeeper:
    image: zookeeper:3.8.3
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/data
      - zookeeper-logs:/datalog

  # API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY=INFO
    networks:
      - stock-network

  # Auth Service
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/stock_monitoring
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    networks:
      - stock-network

  # Profile Service
  profile-service:
    build: ./profile-service
    container_name: profile-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/stock_monitoring
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    networks:
      - stock-network

  # Master Data Service
  master-data-service:
    build: ./master-data-service
    container_name: master-data-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/stock_monitoring
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    networks:
      - stock-network

volumes:
  stock_postgres_data:
  zookeeper-data:
  zookeeper-logs:

networks:
  stock-network:
    driver: bridge
